// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMXeGhUEZPmU7l9rAQ2d6nvRcFkcN8SYc',
    appId: '1:1056407623624:web:12b9a62ff1df8a612852fd',
    messagingSenderId: '1056407623624',
    projectId: 'notes-app-88ab5',
    authDomain: 'notes-app-88ab5.firebaseapp.com',
    storageBucket: 'notes-app-88ab5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBN3l5EqDK4-yoNbtuvOHb2BpHjopyN2s',
    appId: '1:1056407623624:android:030a913479c696182852fd',
    messagingSenderId: '1056407623624',
    projectId: 'notes-app-88ab5',
    storageBucket: 'notes-app-88ab5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACzov3GwCYKLy3HIm1TdlINWide0VDbJA',
    appId: '1:1056407623624:ios:f05f32e630b66d9d2852fd',
    messagingSenderId: '1056407623624',
    projectId: 'notes-app-88ab5',
    storageBucket: 'notes-app-88ab5.firebasestorage.app',
    iosBundleId: 'com.example.eventlyPlan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACzov3GwCYKLy3HIm1TdlINWide0VDbJA',
    appId: '1:1056407623624:ios:f05f32e630b66d9d2852fd',
    messagingSenderId: '1056407623624',
    projectId: 'notes-app-88ab5',
    storageBucket: 'notes-app-88ab5.firebasestorage.app',
    iosBundleId: 'com.example.eventlyPlan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMXeGhUEZPmU7l9rAQ2d6nvRcFkcN8SYc',
    appId: '1:1056407623624:web:91f0ba6ad916c98d2852fd',
    messagingSenderId: '1056407623624',
    projectId: 'notes-app-88ab5',
    authDomain: 'notes-app-88ab5.firebaseapp.com',
    storageBucket: 'notes-app-88ab5.firebasestorage.app',
  );
}
